[UPDATE] test

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -7,6 +7,7 @@ on:
     branches-ignore: [ga-ignore-*]
 
 jobs:
+
   coding-style:
     runs-on: ubuntu-latest
     container: 
@@ -29,4 +30,21 @@ jobs:
             found::$ERROR"
             exit 1
           fi
-            exit 0
+          exit 0
+  compile:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout GH repo
+        uses: actions/checkout@v4
+
+      - name: Compile repository
+        run: make
+
+      - name: Check binary presence
+        run: |
+          if [! -f ./swapupcase]; then
+            echo "::error file=swapupcase, title=Binary
+            Error::Binary not found"
+            exit 1
+          fi
+          exit 0
